language: perl
perl:
  - "5.8"               
  - "5.10"
  - "5.20"              # installs latest perl 5.20 (if not already available)
  - "dev"               # installs latest developer release of perl (e.g. 5.21.8)
  - "blead"             # builds perl from git
matrix:
  #include:
  #  - perl: 5.18
  #    env: COVERAGE=1   # enables coverage+coveralls reporting
  allow_failures:
    - perl: blead       # ignore failures for blead perl
sudo: false             # faster builds as long as you don't need sudo access
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto

#language: perl
#matrix:
# include:
#  - perl: "5.26"
#    env: USE_MAP_TUBE_VERSION=latest
#    env: USE_MAP_TUBE_FORMATTER_VERSION=latest
#  - perl: "5.24"
#    env: WITH_TEST_MAP_TUBE=1
#  - perl: "5.20"
#    env: USE_MAP_TUBE_VERSION=latest
#    env: USE_MAP_TUBE_FORMATTER_VERSION=latest
#  - perl: "5.18"
#    # test with minimum version
#    env: USE_MAP_TUBE_VERSION=3.40
#  - perl: "5.16"
#    env: USE_MAP_TUBE_VERSION=latest
#    env: USE_MAP_TUBE_FORMATTER_VERSION=latest
#  - perl: "5.14"
#    env: USE_MAP_TUBE_VERSION=latest
#    env: USE_MAP_TUBE_FORMATTER_VERSION=latest
#  - perl: "5.12"
#    env: USE_MAP_TUBE_VERSION=latest
#    env: USE_MAP_TUBE_FORMATTER_VERSION=latest
#  - perl: "5.10"
#    env: USE_MAP_TUBE_VERSION=latest
#    env: USE_MAP_TUBE_FORMATTER_VERSION=latest
#  - perl: "5.8"
#    env: USE_MAP_TUBE_VERSION=latest
#    env: USE_MAP_TUBE_FORMATTER_VERSION=latest
#
#
#before_install:
# - '[ "$USE_MAP_TUBE_VERSION" != "latest" ] && cpanm --quiet --notest Map::Tube~"==$USE_MAP_TUBE_VERSION" || true'
# - '[ "$USE_MAP_TUBE_FORMATTER_VERSION" != "latest" ] && cpanm --quiet --notest Map::Tube::Plugin::Formatter~"==$USE_MAP_TUBE_FORMATTER_VERSION" || true'
# - '[ "$WITH_TEST_MAP_TUBE" = 1 ]           && cpanm --quiet --notest Test::Map::Tube                     || true'
#
#after_script:
#  - make distcheck
#  - HARNESS_OPTIONS=j4:c make disttest
#
#branches:
# except:
#  - /appveyor/
#sudo: false
#